tupla = tuple()
tupla = ()
print(type(tupla))
# print(help(tupla))
tupla = ('um')
print(type(tupla))
tupla = ('um',)
print(type(tupla))
print(tupla[0])
cores = ('verde', 'azul', 'branco')
print(cores.count('Azul'))

print(len(cores))
